### ISSUE TITLE
Typo in Documentation, v. 1.0,  p. 6

### ISSUE THREAD

**Issue by ZManni1** [dcpurton/scripture#24]
On page 6 of the documentation, the word *have* should be "half" in the first indented line of text.

“Poetry sections of the Bible often have a first *have* and a parallel second half which is indented a little,” should be: “Poetry sections of the Bible often have a first *half* and a parallel second half which is indented a little.”
(asterisks added)

**Comment by dcpurton** [comment]
Thanks @ZManni1 !

I'm going to do another release soon. I've added quite a lot of features and fixed bugs.
