### ISSUE TITLE
Hypertext link reference to website

### ISSUE THREAD

**Issue by twestley** [dcpurton/scripture#38]
I would like Bible references in the PDF to actively link to Bible Gateway. Here is an example of how to do that using the `hyperref` package:

```
\href{https://www.biblegateway.com/passage/?search=Psalm+86%3A10&version=ESV}{Psalm 86:10}
```

But the following `scripture` code:

```
\begin{scripture}[\href{https://www.biblegateway.com/passage/?search=Psalm+86%3A10&version=ESV}{Psalm 86:10}][version=ESV]
\begin{poetry}
For you are great and do wondrous things;
you alone are God.
\end{poetry}
\end{scripture}
```
results in this error:

```
Paragraph ended before \\environment scripture was complete.
```

What am I doing wrong? Or do you have a better suggestion for doing this?

I apologize if this is not the appropriate way to use issues. I didn't know how else to communicate a question to you.

**Comment by dcpurton** [comment]
This is the perfect way to raise issues @twestley . Thanks for reporting this.

I'd expect this to work.

I'll take a look.

**Comment by dcpurton** [comment]
The problem is with passing the special characters `%` and `&` in as an argument. This is a general problem in LaTeX and special treatment is needed. I don't think this is something I would fix directly in the `scripture` package.

There's probably a better way, and you might get good advice by asking a question on https://tex.stackexchange.com/, but this seems to work OK:

```TeX
\documentclass{article}
\ExplSyntaxOn
\NewDocumentCommand { \linkref } { m }
  {
    \str_set_convert:Nnnn \l_tmpa_str { #1 } { } { utf8/url }
    \str_set:Nn \l_tmpb_str
      { https://www.biblegateway.com/passage/?search= }
    \str_concat:NNN \l_tmpb_str \l_tmpb_str \l_tmpa_str
    \str_put_right:Nn \l_tmpb_str { &version= }
    \href
      { \l_tmpb_str \l__scripture_version_tl }
      { #1 }
  }
\ExplSyntaxOff
\usepackage{hyperref}
\usepackage{scripture}
\scripturesetup{
  reference/format=\linkref{#1},
  version=ESV
}
\begin{document}
\begin{scripture}[Psalm 86:10]
    \begin{poetry}
        For you are great and do wondrous things;
        you alone are God.
    \end{poetry}
\end{scripture}
\end{document}
```

**Comment by twestley** [comment]
Thanks for the workaround solution. I'll try it out.

**Comment by twestley** [comment]
It works great! Except that it suppresses verse numbers. When I run the minimal example above, the \vs{10} does not result in a verse number in the output.

**Comment by dcpurton** [comment]
Just remove the `verse/hide` option. That was just an attempt to match your example.
