### ISSUE TITLE
Feature request: width settings for scripture blocks.

### ISSUE THREAD

**Issue by hanetzer** [dcpurton/scripture#46]
Occasionally one will include a 'hunk' of scripture within a text. As of right now, my rendering puts 'normal'
paragraphs and scripture 'hunks' at the same width, making it a bit tricky to distinguish where one ends and
the other begins (aside from the scripture ref at the end)

**Comment by dcpurton** [comment]
I think I generally envisage this being done using a `quote` or `quotation`environment.

However there is also a `leftmargin` and `rightmargin` option that can be used.

Are these two methods sufficient?
