### ISSUE TITLE
Question: inline scripture quotations?

### ISSUE THREAD

**Issue by hanetzer** [dcpurton/scripture#52]
So normally, you'd either have *all scripture* (as in, making a bible) or separate text blocks (center, displayquote, whatever)
containing the scripture. 

What I'm wondering about, is inline quotations like, "As it says in John 3:16, 'God so loved the world that he gave his only begotten son'", intermingled with otherwise 'normal' text. the begin/end scripture bits doesn't quite flow like one would
hope, so I'm hoping for some guidance here.

**Comment by dcpurton** [comment]
Hmmm. I confess I didn't design with this in mind. 

It would need an `inline` option added that handled the the reference differently. There is always a new paragraph inserted at the end of quotations at the moment.

**Comment by dcpurton** [comment]
Some thoughts on this:

A new option, `inline` could be introduced.

This would need to behave like `compact` and remove internal layout formatting (drop chapters, poetry, etc.). Additionally, it would need to ensure there were no margins or before and after skips.

Some thought would need to be given to quote marks. Should these be specified as options? They would need to fall between the quotation and the reference (if a reference was specified).

Rather than an environment, should an inline command be provided, e.g., `\textscripture[reference][options]{text}`? This could automatically set the `inline` option and would be easier to typeset.

**Comment by hanetzer** [comment]
yeah, I was imagining something like `\textscripture....` when I brought this up.

**Comment by dcpurton** [comment]
@hanetzer  I've had a go at adding an interface and code for this. Not pushed yet.

What do you think as far as usage, flexibility and interface goes

The `inline/begin` and `inline/end` options allow for a kind of poor man's localised quotation marks.

```TeX
\documentclass[a4paper]{article}
\input{regression-test}
\usepackage[T1]{fontenc}
\usepackage{scripture}
\scripturesetup{
  redletter,
  colour=blue,
}
\pagestyle{empty}
\begin{document}
\START
\showoutput
Lead in text: \textscripture[John 3:16]{\vs{16}For God so loved the world
that he gave his one and only Son, that whoever believes in him shall not
perish but have eternal life.} Lead out text.

\bigskip

Lead in text: \textscripture[John 3:3]{\vs{3}Jesus replied, \redletteron ‘Very
truly I tell you, no one can see the kingdom of God unless they are born
again.’\redletteroff} Lead out text.

\bigskip

Lead in text:
\begin{scripture}[Isaiah 1:2][inline, inline/begin=«\,, inline/end=\,»]
  \begin{poetry}
    \vs{2}Hear me, you heavens! Listen, earth!
    For the \name{Lord} has spoken:

    ‘I reared children and brought them up,
    but they have rebelled against me.
  \end{poetry}
\end{scripture}
Lead out text.

\bigskip

Lead in text:
\begin{scripture}[2 Kings 18:18--19][inline]
  \vs{18}They called for the king; and Eliakim son of Hilkiah the palace
  administrator, Shebna the secretary, and Joah son of Asaph the recorder went
  out to them.

  \vs{19}The field commander said to them, ‘Tell Hezekiah:

  \begin{narrow}
    ‘“This is what the great king, the king of Assyria, says: on what are you
    basing this confidence of yours?
  \end{narrow}
\end{scripture}
Lead out text.

\bigskip

Lead in text:
\begin{scripture}[Genesis 1:1--2][inline, inline/begin={,,\,}, inline/end=\,'']
  \begin{hanging}
    \ch{1}In the beginning God created the heavens and the earth. \vs{2}Now the
    earth was formless and empty, darkness was over the surface of the deep,
    and the Spirit of God was hovering over the waters.
  \end{hanging}
\end{scripture}
Lead out text.

\bigskip

Lead in text:
\begin{scripture}[Daniel 5:25][inline]
  \vs{25}‘This is the inscription that was written:
  \begin{center}
    \textsc{mene, mene, tekel, parsin}
  \end{center}
\end{scripture}
Lead out text.

\bigskip

Lead in text.
\begin{scripture}[Isaiah 40:5][inline]
  \begin{poetry}[belowskip = 0pt]
    \vs{5}And the glory of the \name{Lord} will be revealed,
    and all people will see it together.
  \end{poetry}

  \begin{flushright}[aboveskip = 0pt]
    For the mouth of the \name{Lord} \\
    has spoken.’
  \end{flushright}
\end{scripture}
Lead out text.

\bigskip

Lead in text:
\begin{scripture}[1 Corinthians 10:31--11:1][inline]
  \begin{midparachap}
    \vs{31}So whether you eat or drink or whatever you do, do it all for the
    glory of God. \vs{32}Do not cause anyone to stumble, whether Jews, Greeks
    or the church of God---\vs{33}even as I try to please everyone in every
    way. For I am not seeking my own good but the good of many, so that they
    may be saved. \ch{11}Follow my example, as I follow the example of Christ.
  \end{midparachap}
\end{scripture}
Lead out text.
\end{document}
```

![issue52](https://user-images.githubusercontent.com/6268044/211018268-183480ba-1510-4a63-b248-9ec1ed636bce.png)

**Comment by hanetzer** [comment]
Yeah, that very much looks good. Sorry for the delay, but I had $dayjob to deal with.
